{
 "title": "NGINX Overview",
 "description": "NGINX exporter",
 "tags": [
  "nginx",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "NGINX Down List",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "nginx_up==0", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "NGINX Up Number",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(nginx_up)", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "NGINX Up List",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "targets": [
    { "expr": "nginx_up==1", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Total requests",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Processed connections Top5",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,irate(nginx_connections_accepted_total[5m]))",
     "legendFormat": "{{host}} accepted"
    },
    {
     "expr": "topk(5,irate(nginx_connections_handled_total[5m]))",
     "legendFormat": "{{host}} handled"
    }
   ]
  },
  {
   "title": "Active Connections Top10",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,nginx_connections_active_total)",
     "legendFormat": "{{host}} active"
    }
   ]
  }
 ]
}